services:
  app:
    image: filippogrande/interesting-items:backend-latest
    pull_policy: always
    ports:
      - "8004:8004"
    environment:
      # URL pubblico/di rete per costruire link interni (usato dal bot)
      - BASE_URL=${BASE_URL:-http://localhost:3002}
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
      - ALLOWED_TELEGRAM_USER_IDS=${ALLOWED_TELEGRAM_USER_IDS}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/products
    volumes:
      - /mnt/applicazioni/interesting-items/storage_data:/app/storage_data
      - /mnt/applicazioni/interesting-items/images:/app/images
      - /mnt/applicazioni/interesting-items/tmp:/app/tmp
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - /mnt/applicazioni/interesting-items/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
  frontend:
    image: filippogrande/interesting-items:frontend-latest
    pull_policy: always
    ports:
      - "3002:80"
    depends_on:
      - app
    restart: unless-stopped
volumes:
  redis_data:

