services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-filippogrande}/interesting-items:backend-latest
    ports:
      - "8004:8004"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
      - ALLOWED_TELEGRAM_USER_IDS=${ALLOWED_TELEGRAM_USER_IDS}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/products
    volumes:
      - ./backend/storage:/app/storage
      - images_data:/app/images
      - ./backend/tmp:/app/tmp
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-filippogrande}/interesting-items:frontend-latest
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped
volumes:
  db_data:
  redis_data:
  images_data:

